---
linter_rules:
  python:
    enabled: true
    version: "3.8"
    options: "--format=pylint"
    include_paths: "**/*.py"

  markdown:
    enabled: true
    options: "--config=markdownlint.yaml"
    include_paths: "**/*.md"

  yaml:
    enabled: true
    include_paths: "**/*.{yaml,yml}"
    line-length: disable
    new-lines: disable
    truthy: disable