---
name: Megalinter

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main

jobs:
  megalinter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up MegaLinter
        uses: github/super-linter@v4
        env:
          VALIDATE_DOCKERFILE: false
          VALIDATE_MAKEFILE: false
          VALIDATE_PYTHON: true
          VALIDATE_YAML: true
          VALIDATE_MD: true
          SUPERLINTER_RULES_PATH: .github/linters
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
